spring:
  application:
    name: board-game-manager

management:
  security:
    enabled: false # disable the security on the Actuator endpoints.
  endpoints:
    web:
      exposure:
        include: health, loggers # Enable actuator endpoints

jwt:
  signing:
    key: ${JWT_SIGNING_KEY}

aws:
  localStack:
      enabled: ${LOCALSTACK_ENABLED}
      endpoint:
        url: ${AWS_ENDPOINT_URL}
  paramstore:
    prefix: /config
    defaultContext: board-game-manager
    profileSeparator: _
  dynamodb:
    user:
      table: ${AWS_DYNAMODB_USER_TABLE}

splunk:
  http:
    url: ${SPLUNK_HTTP_URL}
    token: ${SPLUNK_HTTP_TOKEN}
    host: ${SPLUNK_HTTP_HOST}
    index: ${SPLUNK_HTTP_INDEX}
    source: ${SPLUNK_HTTP_SOURCE}
