spring:
  application:
    name: board-game-manager

aws:
  localStack:
      enabled: ${LOCALSTACK_ENABLED}
      endpoint:
        url: ${AWS_ENDPOINT_URL}
  paramstore:
    prefix: /config
    defaultContext: board-game-manager
    profileSeparator: _

splunk:
  http:
    url: ${SPLUNK_HTTP_URL}
    token: ${SPLUNK_HTTP_TOKEN}
    host: ${SPLUNK_HTTP_HOST}
    index: ${SPLUNK_HTTP_INDEX}
    source: ${SPLUNK_HTTP_SOURCE}
